---

name: Feature request
description: Suggest an idea for this project
title: "Feature: "
labels: ['enhancement', 'triage']

body:
  - type: markdown
    attributes:
      value: |
        Please make sure to go through these steps **before opening an issue**:

        - [ ] Read the documentation to make sure the feature does not yet exist:
        [Docs](https://ansible-webui.readthedocs.io/)

        - [ ] Make sure the feature is in-scope. We cannot extend the basic functionality of Ansible itself:
        [Ansible Docs](https://docs.ansible.com/ansible/2.8/user_guide/playbooks_best_practices.html#directory-layout)

        The Ansible-WebUI project tries to keep its codebase as simple & small as possible.
        Be aware we will not implement all 'nice-to-have' or 'fancy' features.

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: What version of our software are you running?
      options:
        - Unknown
        - Frontend (User Interface)
        - Ansible (Job Execution)
        - Backend (API)
        - Service (Job Scheduling, Job Preparation)
        - Database
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A clear and concise description of:

        * what you want to happen
        * what you are missing
        * why that would be beneficial
    validations:
      required: true
