---

on:
  push:
    tags:
     - '*'

jobs:
  publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements_build.txt
        shell: bash

      - name: Extract tag name
        id: version
        run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3 | cut -c 2-)

      - name: Update version in setup.py
        run: >-
          sed -i 's/version=.*/version="${{ steps.version.outputs.TAG_NAME }}",/g' setup.py
          sed -i 's/VERSION =.*/VERSION = "${{ steps.version.outputs.TAG_NAME }}"/g' ansible-webui/aw/config/hardcoded.py

      - name: Building
        run: python3 -m build
        shell: bash

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
