---

name: Test

on:
  push:
    branches: [latest]
    paths:
      - '**.py'
      - '.github/workflows/test.yml'
      - 'requirements_test.txt'
  pull_request:
    branches: [latest]
    paths:
      - '**.py'
      - '**.yml'
      - '.github/workflows/test.yml'
      - 'requirements_test.txt'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements_test.txt >/dev/null
          pip install -r requirements_build.txt >/dev/null
          pip install -r requirements.txt >/dev/null
        shell: bash

      - name: Testing DB migrations for errors & warnings (1/3)
        run: |
          python3 manage.py makemigrations
          m1=$(python3 manage.py makemigrations 2>&1)
          if echo "$m1" | grep -q 'WARNING'; then exit 1;fi
        shell: bash
        working-directory: src/ansible-webui/

      - name: Testing DB migrations for errors & warnings (2/3)
        run: |
          python3 manage.py makemigrations aw
          m2=$(python3 manage.py migrate aw 2>&1)
          if echo "$m2" | grep -q 'WARNING'; then exit 1;fi
        shell: bash
        working-directory: src/ansible-webui/

      - name: Testing DB migrations for errors & warnings (3/3)
        run: |
          python3 manage.py migrate
          m3=$(python3 manage.py migrate 2>&1)
          if echo "$m3" | grep -q 'WARNING'; then exit 1;fi
        shell: bash
        working-directory: src/ansible-webui/

      - name: Testing to start Ansible-WebUI
        run: |
          set +e
          timeout 2 python3 src/ansible-webui
          ec="$?"
          if [[ "$ec" != "124" ]]
          then
            exit 1
          fi
        shell: bash

      - name: Running Tests
        run: python3 -m pytest
        shell: bash
